/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package squarelinks

class App {
    val stageOne: String
        get() {
            val cut = SquareLinks()
            repeat(5) { cut.newSquare() }
            println("Is valid: ${cut.validate()}")
            return cut.links.joinToString("")
        }
}

fun main() {
    println(App().stageOne)
}
