/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package squarelinks

class App {
    internal val operator = Operator()

    companion object {
        var Zs: Int = 0
    }
}

fun main() {
    println("Enter how many zeros the hash must start with:")
    App.Zs = readln().toInt()
    App().operator.mining()
}
